### PR TITLE
Fix Chrome timeout in Travis builds

### LINKED ISSUE #9: 1.0 doesn’t work on CI
I very like new features from Estimo 1.0. I already tried to use it in Size Limit 
https://github.com/ai/size-limit/commit/89b59df42d19fb88a8f440649ba4f5bf97c4a469

Unfortunately, I found an issue. On CI without Chrome estimo freezes (have no result for 20 seconds)
https://travis-ci.org/ai/size-limit/jobs/547958183

My suggestions:
1. We need to test estimo with Chrome and without on Travis CI. You can use `matrix` to use `addons` only in one case.
2. We need to find and fix this bug. Travis CI fixes will help.

### PR DESCRIPTION
**Pull request by creazero**
Turns out, Travis image has its own Chrome, which doesn't want to start for some reason. So I added a version guard for it (>= 75) and additional env vars from puppeteer's `install.js`.

Fixes #9 
@ai

### CODE REVIEW

File: scripts/findChrome.js [hunk 1]
```diff
@@ -197,6 +198,24 @@ async function downloadChromium() {
   }
 }
 
+function isSuitableVersion(executablePath) {
+  let versionOutput
+  // in case installed Chrome is not runnable
+  try {
+    versionOutput = execSync(`${executablePath} --version`).toString()
```
Comment (ai) [inline scripts/findChrome.js]: Let’s use async `exec` if we already have `async`/`await` in the code (so using async code till be very easy)

File: scripts/findChrome.js [hunk 2]
```diff
@@ -197,6 +198,24 @@ async function downloadChromium() {
...
+  } catch (e) {
+    return false
+  }
+  const versionRe = /(Google Chrome|Chromium) ([0-9]{2}).*/
+
+  const match = versionOutput.match(versionRe)
+  if (match && match[2]) {
+    const version = +match[2]
+    return version >= 75
```
Comment (ai) [inline scripts/findChrome.js]: We need to move it to `const` in the beginning of the file

File: scripts/findChrome.js [hunk 3]
```diff
@@ -171,7 +171,8 @@ async function downloadChromium() {
     path: chromeTempPath,
   })
 
-  const revision = pptrCoreJson.puppeteer.chromium_revision
+  const revision = process.env.PUPPETEER_CHROMIUM_REVISION || process.env.npm_config_puppeteer_chromium_revision
```
Comment (ai) [inline scripts/findChrome.js]: We need more `process.env` to copy. For instance, we need `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` and `PUPPETEER_DOWNLOAD_HOST`.

File: scripts/findChrome.js (hunk 2 above)
Comment (creazero) [reply scripts/findChrome.js]: Will it be right to add a non-const variable to the const block? Since we don't know local version at start.

File: scripts/findChrome.js (hunk 1 above)
Comment (creazero) [reply scripts/findChrome.js]: Done.

File: scripts/findChrome.js (hunk 3 above)
Comment (creazero) [reply scripts/findChrome.js]: Added `DOWNLOAD_HOST` and all kinds of options to skip download.

**Comment by ai** [comment]
@mbalabash LGTM. We can release it under patch (as downloader fix) or minor (since we added new env variables) release.

File: scripts/findChrome.js (hunk 2 above)
Comment (ai) [reply scripts/findChrome.js]: I am talking about

```js
const MIN_CHROME_VERSION = 75
```

We will change this version requirement tin the future

**Comment by mbalabash** [comment]
Wow, awesome work!
Thanks you guys
